version: "3.9"
services:
  dataproducer:
    build:
      context: ./data_producer
    ports:
      - 3000:3000
    environment:
      - BEARER_TOKEN=xxx
  dataconsumer:
    build:
      context: ./data_consumer
    ports:
      - 5000:5000
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db