apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataproducer-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataproducer
  template:
    metadata:
      labels:
        app: dataproducer
    spec:
      containers:
        - name: dataproducer
          image: parhambrz/dataproducer:latest
          env:
          - name: BEARER_TOKEN
            value: "xxx"
  
---
# Setup ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: dataproducer-clusterip-svc
spec:
  type: ClusterIP
  selector:
    app: dataproducer
  ports:
    - name: dataproducer
      protocol: TCP
      port: 80
      targetPort: 80
  